# -*- coding: utf-8 -*-
"""Monte Carlo Simulation for Reinsurance Risk Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j_bnHNBZ_pnbYxfGWNOGt7LBsJiHxwH

# Monte Carlo Simulation for Reinsurance Risk Assessment

## 1. Project Overview
This project develops a **Monte Carlo Simulation** engine to simulate the aggregate loss of an insurance portfolio. By incorporating per-claim policy terms (Deductibles and Limits) and reinsurance structures (Retention), we evaluate the risk distribution from both the insurer's and reinsurer's perspectives.

**Key Objectives:**
* Model claim severity using **heavy-tailed distributions** (Lognormal, Pareto).
* **Risk Quantification**: Utilize **VaR (Value at Risk)** to measure extreme tail risks and solvency requirements.   
* Note: Model supports Lognormal, Pareto, Gamma, and Exponential distributions. All distribution-specific parameters are modularly defined within the core functions to allow for seamless benchmarking of various risk profiles.

## 2. Stochastic Modeling & Parameter Setup
We assume claim frequency follows a **Poisson distribution**, and claim severity can be configured with various distributions to reflect different risk profiles.

"""

import numpy as np
import pandas as pd

# Define function
# Severity distributions 產生損失金額 -----------------------------

def generate_severity(n_claims, dist, params):

    if dist == "lognormal":
        mu, sigma = params
        return np.random.lognormal(mu, sigma, n_claims)

    elif dist == "gamma":
        shape, scale = params
        return np.random.gamma(shape, scale, n_claims)

    elif dist == "exponential":
        scale = params[0]
        return np.random.exponential(scale, n_claims)

    elif dist == "pareto":
        shape = params[0]
        return (np.random.pareto(shape, n_claims) + 1) * 3000

    else:
        raise ValueError("Unsupported distribution")


# Policy structure (deductible & limit) -----------------------------

def compute_payments(claim_sizes, deductible, limit):

    payments = []

    for claim in claim_sizes:

        # deductible
        payment = max(0, claim - deductible)

        # policy limit
        payment = min(payment, limit)

        payments.append(payment)

    return np.array(payments)

# Per-claim reinsurance -----------------------------

def apply_reinsurance(payments, retention):

    insurer_claims = np.minimum(payments, retention)
    reinsurer_claims = np.maximum(0, payments - retention)

    return insurer_claims.sum(), reinsurer_claims.sum()

# Simulation -----------------------------

def per_simulation(n_policy, lambda_freq, dist, params, deductible, limit, retention):

    # frequency - 決定理賠claims次數
    n_claims = np.random.poisson(lambda_freq * n_policy)

    if n_claims == 0:
        return 0,0,0, np.array([])

    # severity - 隨機產生每件理賠案件金額
    claim_sizes = generate_severity(n_claims, dist, params)

    # 計算原始總損失 (Ground-up Loss)
    total_raw_loss = claim_sizes.sum()

    # apply policy terms
    payments = compute_payments(claim_sizes, deductible, limit)

    # reinsurance
    insurer_loss, reinsurer_loss = apply_reinsurance(payments, retention)

    return insurer_loss, reinsurer_loss, total_raw_loss, claim_sizes

# Monte Carlo simulation -----------------------------

def run_simulation(n_sim, n_policy, lambda_freq, dist, params, deductible, limit, retention):
    raw_losses = []
    insurer_losses = []
    reinsurer_losses = []
    all_individual_claims = []
    for i in range(n_sim):
        insurer_loss, reinsurer_loss, raw, individual_claims = per_simulation(n_policy, lambda_freq, dist, params, deductible, limit, retention)
        insurer_losses.append(insurer_loss)
        reinsurer_losses.append(reinsurer_loss)
        raw_losses.append(raw)
        all_individual_claims.extend(individual_claims)
    return np.array(insurer_losses), np.array(reinsurer_losses), np.array(raw_losses), np.array(all_individual_claims)

""" ## 3. Simulation Results: Lognormal (Baseline)
The **Lognormal model** serves as the baseline with **10,000 simulations**, I aggregate the annual losses to calculate key solvency metrics.
**Configuration:**
* **Portfolio Size**:  _n_policy = 1,000_
* **Claim Frequency**:  _lambda_freq = 0.2_ (Poisson)
* **Severity Distribution**:  _Lognormal(mu=8, sigma=1)_
* **Policy Terms**:  _Deductible = 1,000_, _Limit = 50,000_
* **Reinsurance**:  _Retention = 20,000_
"""

np.random.seed(42)
insurer, reinsurer, raw, per = run_simulation(n_sim = 10000, n_policy = 1000, lambda_freq = 0.2, dist = "lognormal", params = (8,1), deductible = 1000,
                                    limit = 50000, retention = 20000)

results = pd.DataFrame({"raw": raw,"insurer": insurer,"reinsurer": reinsurer})
raw_loss = results["raw"].mean()
expected_loss = results["insurer"].mean()
var_95 = results["insurer"].quantile(0.95)
var_99 = results["insurer"].quantile(0.99)

# statistics
print("Statistics:\n", results.describe().map(lambda y: f"{y:,.2f}"))
print(f"Expected Raw Loss: {raw_loss:,.0f}")
print(f"Expected Loss: {expected_loss:,.0f}")
print(f"VaR 95%: {var_95:,.0f}")
print(f"VaR 99%: {var_99:,.0f}")

# 實驗 B：Pareto 分配 (Pareto shape = 2.5)------------------------------------
np.random.seed(42)
insurer_p, reinsurer_p, raw_p, per_p = run_simulation(
    n_sim=10000, n_policy=1000, lambda_freq=0.2,
    dist="pareto", params=(2.5,),
    deductible=1000, limit=50000, retention=20000)

results_p = pd.DataFrame({"raw": raw_p,"insurer": insurer_p,"reinsurer": reinsurer_p})
raw_loss_p = results_p['raw'].mean()
expected_loss_p = results_p["insurer"].mean()
var_95_p = results_p["insurer"].quantile(0.95)
var_99_p = results_p["insurer"].quantile(0.99)

print("Statistics:\n", results_p.describe().map(lambda y: f"{y:,.2f}"))
print(f"Expected Raw Loss: {raw_loss_p:,.0f}")
print(f"Expected Loss: {expected_loss_p:,.0f}")
print(f"Pareto VaR 95%: {var_95_p:,.0f}")
print(f"Pareto VaR 99%: {var_99_p:,.0f}")